# Generated by Django 3.2.5 on 2021-10-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientId', models.IntegerField()),
                ('price', models.FloatField()),
                ('isFilled', models.BooleanField()),
            ],
            options={
                'ordering': ['isFilled'],
            },
        ),
        migrations.CreateModel(
            name='OrderPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField()),
                ('itemId', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('checked', models.BooleanField()),
            ],
            options={
                'ordering': ['orderId'],
            },
        ),
    ]
