# Generated by Django 3.2.5 on 2021-10-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_completeorder_orderpair'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderPair',
            new_name='Item_Order',
        ),
        migrations.RenameModel(
            old_name='CompleteOrder',
            new_name='Order',
        ),
    ]
